version: '3.1'

services:

  php:
    build: .
    working_dir: '/var/www'
    volumes:
      - './:/var/www:cached'
    env_file:
      - ./.env
    environment:
      - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/var/www/vendor/bin
    hostname: ${PROJECT_BASE_URL}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.php.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.services.php.loadbalancer.server.port=80"

  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    volumes:
      - "./:/var/www/html"
    environment:
      JOOMLA_DB_HOST: ${JOOMLA_DB_HOST}
      JOOMLA_DB_PASSWORD: ${JOOMLA_DB_PASSWORD}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joomla.rule=Host(`${PROJECT_BASE_URL}`)"
      - "traefik.http.services.joomla.loadbalancer.server.port=80"

  joomladb:
    image: mysql:5.7
    ports:
      - ${JOOMLA_DB_PORT}
    restart: always
    volumes:
      - "./data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${JOOMLA_DB_PASSWORD}

  phpmyadmin:
    image: phpmyadmin:5.2-apache
    restart: always
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=${JOOMLA_DB_USER}
      - MYSQL_PASSWORD=${JOOMLA_DB_PASSWORD}
    labels:
      - "traefik.http.routers.phpmyadmin.rule=Host(`phpmyadmin.${PROJECT_BASE_URL}`)"
      - "traefik.http.services.phpmyadmin.loadbalancer.server.port=80"

  traefik:
    image: "traefik:2.9"
    command: --api.insecure=true --providers.docker
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"